### PR TITLE
Update credits.md

### LINKED ISSUE #17: Update Credits.md
Some packages are missing (ex. nedb-promises) some need to be removed (ex. nedb) and some links need to be changed ex. youtube-chat to @freetube/youtube-chat

Current freetube dependencies can be found here https://github.com/FreeTubeApp/FreeTube/blob/c14aeab8efcc431f4dda9184a7c07a8f3bdcd047/package.json#L53

### PR DESCRIPTION
**Pull request by efb4f5ff-1298-471a-8973-3d47447115dc**
closes #17

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]
Nice on aligning in source code
Much easier to read

**Review by absidue — DISMISSED** [review]

**Review by efb4f5ff-1298-471a-8973-3d47447115dc — COMMENTED** [review]
todo: 

- [x] remove node-forge when https://github.com/FreeTubeApp/FreeTube/pull/2276 is merged
- [x] remove bulma-pro and videojs-abloop when https://github.com/FreeTubeApp/FreeTube/pull/2278 is merged
- [ ] remove dateformat when https://github.com/FreeTubeApp/FreeTube/pull/2244 is merged

**Review by PikachuEXE — APPROVED** [review]

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ChunkyProgrammer 😬

**Comment by ChunkyProgrammer** [comment]
Yt-trending-scraper and i think yt-dash-manifest should be changed

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@ChunkyProgrammer yeah that is what i also thought but i checked the dependency graph and saw that its linked to another repo

https://github.com/FreeTubeApp/FreeTube/network/dependencies

**Comment by absidue** [comment]
@ChunkyProgrammer FreeTube still uses the old one as the identical version on the FreeTubeApp org is broken see the issue I created about it here: https://github.com/FreeTubeApp/yt-dash-manifest-generator/issues/2

**Comment by ChunkyProgrammer** [comment]
you're right, i thought we had switch to the FreeTube  versions I guess that was just for the other modules.

**Review by ChunkyProgrammer — APPROVED** [review]

**Pull request merged**
